fix(helm): add global.security.allowInsecureImages for bitnamilegacy images
The new Bitnami Helm charts (postgresql 12.1.5, zookeeper 13.8.7, etc.)
include image signature verification that rejects non-standard images
like bitnamilegacy. This causes Helm install to fail with:

  ERROR: Original containers have been substituted for unrecognized ones.
  Unrecognized images: docker.io/bitnamilegacy/zookeeper:3.9.3-debian-12-r21

Setting global.security.allowInsecureImages: true allows the use of
bitnamilegacy images with the newer chart versions.

Reference: https://github.com/bitnami/charts/issues/30850